output   = "internal/database/pqmodels"
pkgname  = "pqmodels"
wipe     = true
no-tests = true
[psql]
  dbname = "flagroll"
  host   = "localhost"
  port   = 5432
  user   = "postgres"
  pass   = "postgres"
  sslmode = "disable"
  blacklist = ["goose_db_version"]