// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package pqmodels

var TableNames = struct {
	APIKeys      string
	FeatureFlags string
	Users        string
}{
	APIKeys:      "api_keys",
	FeatureFlags: "feature_flags",
	Users:        "users",
}
