// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"github.com/novychok/flagroll/platform/internal/handler/platformApiv1"
)

// Injectors from wire.go:

func Init() (*App, func(), error) {
	server := platformapiv1.NewServer()
	app := New(server)
	return app, func() {
	}, nil
}
